name: Docker build image

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:

  build:

    runs-on: 'ubuntu-latest'

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push docker image single process
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: camptocamp/georchestra-saslauthd:latest, camptocamp/georchestra-saslauthd:build-${{ env.timestamp }}
